-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Campus"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Campus" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Docente"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Code" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Docente" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Evento"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Capacity" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TipoEventoId" integer NOT NULL,
    "SubtipoEventoId" integer NOT NULL,
    "OrganizadorId" integer NOT NULL,
    "DocenteId" bigint NOT NULL,
    "UbicacionId" integer NOT NULL,
    CONSTRAINT "PK_Evento" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."EventoCampus"
(
    "EventoId" integer NOT NULL,
    "CampusId" integer NOT NULL,
    CONSTRAINT "PK_EventoCampus" PRIMARY KEY ("EventoId", "CampusId")
);

CREATE TABLE IF NOT EXISTS public."Organizador"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Organizador" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."SubtipoEvento"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_SubtipoEvento" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TipoEvento"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_TipoEvento" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Ubicacion"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Modality" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Ubicacion" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "FK_Evento_Docente_DocenteId" FOREIGN KEY ("DocenteId")
    REFERENCES public."Docente" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Evento_DocenteId"
    ON public."Evento"("DocenteId");


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "FK_Evento_Organizador_OrganizadorId" FOREIGN KEY ("OrganizadorId")
    REFERENCES public."Organizador" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Evento_OrganizadorId"
    ON public."Evento"("OrganizadorId");


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "FK_Evento_SubtipoEvento_SubtipoEventoId" FOREIGN KEY ("SubtipoEventoId")
    REFERENCES public."SubtipoEvento" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Evento_SubtipoEventoId"
    ON public."Evento"("SubtipoEventoId");


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "FK_Evento_TipoEvento_TipoEventoId" FOREIGN KEY ("TipoEventoId")
    REFERENCES public."TipoEvento" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Evento_TipoEventoId"
    ON public."Evento"("TipoEventoId");


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "FK_Evento_Ubicacion_UbicacionId" FOREIGN KEY ("UbicacionId")
    REFERENCES public."Ubicacion" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Evento_UbicacionId"
    ON public."Evento"("UbicacionId");


ALTER TABLE IF EXISTS public."EventoCampus"
    ADD CONSTRAINT "FK_EventoCampus_Campus_CampusId" FOREIGN KEY ("CampusId")
    REFERENCES public."Campus" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_EventoCampus_CampusId"
    ON public."EventoCampus"("CampusId");


ALTER TABLE IF EXISTS public."EventoCampus"
    ADD CONSTRAINT "FK_EventoCampus_Evento_EventoId" FOREIGN KEY ("EventoId")
    REFERENCES public."Evento" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;